services:
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    entrypoint: ./entrypoint.sh
    command: "rails s -b 0.0.0.0"

volumes:
  bundle:
